---

- name: Include default.yml
  include: default.yml

- name: Install holland-common pkgs on Redhat base
  yum: name=holland-common state=present
  when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int < 7

- name: Install holland-common on Redhat 7 base
  include: RHEL7_common.yml
  when: ansible_os_family == 'RedHat' and ansible_lsb.major_release|int == 7

- name: Install holland-common reqs on Debian base
  apt: name=python-mysqldb state=present
  when: ansible_os_family == 'Debian'

- name: Download holland-common .deb files for local install
  copy: src=holland-common_{{holland_version}}_all.deb dest=/tmp/holland-common_{{holland_version}}_all.deb
  when: ansible_os_family == 'Debian'
  register: deb_common_dl

- name: Install holland-common .deb file
  apt: deb=/tmp/holland-common_{{holland_version}}_all.deb state=installed
  when: ansible_os_family == 'Debian' and deb_common_dl|changed
  register: deb_common_installed

- name: Cleanup holland-common .deb file
  file: dest=/tmp/holland-common_{{holland_version}}_all.deb state=absent
  when: ansible_os_family == 'Debian' and deb_common_installed|changed
