---
### PHP7 VARS
'packages': [
                "libapache2-mod-php7.0",
                "php7.0-cli",
                "php-pear",
                "php7.0-mysql",
                "php7.0-gd",
                "php7.0-dev",
                "php7.0-curl"
                ]
'session_save_path': "/var/lib/php7/session"
'php_ini': "/etc/php/7.0/apache2/php.ini"

### PHP-FPM VARS
'php_fpm': 'php7-fpm'
'php_fpm_path': '/etc/php7/fpm/pool.d'


### APACHE2 VARS
'apache_ver': 'v24'

'modules': [ 
        "access_compat",
        "alias",
        "auth_basic",
        "authn_core",
        "authn_file",
        "authz_core",
        "authz_groupfile",
        "authz_host",
        "authz_user",
        "autoindex",
        "deflate",
        "dir",
        "env",
        "filter",
        "mime",
        "mpm_prefork",
        "negotiation",
        "rewrite",
        "setenvif",
        "socache_shmcb",
        "ssl",
        "status" ]


'module_configs': [
                    "alias",
                    "autoindex",
                    "deflate",
                    "dir",
                    "mime",
                    "mpm_prefork",
                    "negotiation",
                    "php7",
                    "setenvif",
                    "ssl",
                    "status"
                    ]


### PHPMYADMIN VARS
'apache_conf_path': '/etc/apache2/conf-enabled'

