---
# Generic Playbook to install and configure apache as an example

#- include_vars: "{{ansible_os_family}}.yml" 

- include: install.yml
- include: domain.yml
- include: lamp.yml
- include: firewall.yml
