---
- name: Restart apache
  service: name={{ apache }} state=restarted
  when: ansible_os_family == 'Debian'

- name: Restart apache
  service: name={{ apache }} state=restarted
  when: ansible_os_family == 'RedHat'
